# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-26 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_organization_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='api_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
