# Generated by Django 4.1.7 on 2023-03-10 22:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "questionnaire",
            "0004_alter_answer_yesno_alter_category_questionnaire_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Organization",
            new_name="Survey",
        ),
    ]
