# Generated by Django 4.1.7 on 2023-03-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0005_rename_organization_survey"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activeorganization",
            old_name="organization",
            new_name="survey",
        ),
    ]
