# Generated by Django 4.1.7 on 2023-03-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0006_rename_organization_activeorganization_survey"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="organization",
            new_name="survey",
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("survey", "question")},
        ),
    ]
