# Generated by Django 4.1.7 on 2023-03-13 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("questionnaire", "0007_rename_organization_answer_survey_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ActiveOrganization",
            new_name="ActiveSurvey",
        ),
    ]
