# Generated by Django 4.1.7 on 2023-05-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0011_document_tqip"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="tqip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey",
                to="questionnaire.tqip",
            ),
        ),
        migrations.AlterField(
            model_name="tqip",
            name="content",
            field=models.FileField(upload_to="tqip"),
        ),
    ]
