# Generated by Django 4.1.7 on 2023-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0012_survey_tqip_alter_tqip_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="q_type",
            field=models.CharField(
                choices=[
                    ("combo", "Combo Box"),
                    ("check", "Check Boxes"),
                    ("text", "Text Field"),
                    ("int", "Integer Field"),
                    ("unit", "Unit Int Field"),
                    ("float", "Float Field"),
                    ("bool", "Yes or No"),
                ],
                max_length=5,
            ),
        ),
    ]
