# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-12 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
