# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-25 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_auto_20160509_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
