# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-28 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='questionnaire',
            field=models.TextField(default='center'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('combo', 'Combo Box'), ('check', 'Check Boxes'), ('text', 'Text Field'), ('int', 'Integer Field'), ('unit', 'Unit Int Field'), ('bool', 'Yes or No')], max_length=5),
        ),
    ]
