# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-10 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_auto_20170112_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='f_type',
            field=models.CharField(blank=True, choices=[('month_to_date', 'Number of months to date'), ('example', 'Example')], max_length=50, null=True),
        ),
    ]
