# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0023_organization_org_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Organization'),
        ),
    ]
